### ISSUE TITLE
are you want ban

### ISSUE THREAD

**Issue by 1337heker** [neel0210/dynamic#1]
line 53
```
./lpmake --metadata-size 65536 --super-name super --metadata-slots 2 --device super:6539968512 --group main:4187590970 --partition system:readonly:2330120192:main --image system=./system.img --partition vendor:readonly:646946816:main --image vendor=./vendor.img --partition odm:readonly:4349952:main --image odm=./odm.img --sparse --output ./super.img
```

the number in --devices, after super is partition size of super which means not every phone, will have the same
--group after main is the sum of all partitions files sizes. and not everyone repacking exact same super.img
then for each --partition the numbers are again size of how much the system/vendor/product files take

right now its just some code that works for your phone, but not others.

**Comment by neel0210** [comment]
are you want ban? we know that already and got fixed even just didnt pushed update

**Comment by 1337heker** [comment]
> are you want ban? we know that already and got fixed even just didnt pushed update

yes , i am want ban . why not pushed ?
